---
author: |
    | William Findlay
title: |
    | COMP4108 Final Exam Practice
date: \today
#bibliography: untitled.bib
biblio-style: ieee
subparagraph: yes
classoption: 12pt
header-includes:
    - \usepackage{findlayrmd}
output:
    pdf_document:
        citation_package: biblatex
        number_sections: true
        fig_crop: true
        fig_caption: true
        keep_tex: false
        pandoc_args: ["--listings"]
---
```{r,include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(kableExtra.latex.load_packages = FALSE)
library(kableExtra)
library(lubridate)
```
<!-- Setup -->
\pagestyle{fancy}
\setlength{\headheight}{15pt}
\counterwithin{lstlisting}{section}
\renewcommand{\maketitle}{\oldmaketitle}

<!-- Title page -->
\maketitle
\thispagestyle{empty}

<!-- Table of contents -->
\newpage
\pagenumbering{roman}
\tableofcontents

<!-- List of figs, tables, listings -->
\newpage
\listoffigures
\newpage
\listoftables
\newpage
\lstlistoflistings

<!-- Setup the rest of the document -->
\newpage
\pagenumbering{arabic}
\setcounter{page}{1}

# Preamble

## Textbook

- [here is a link to "Tools and Jewels"](http://people.scs.carleton.ca/~paulv/toolsjewels.html)

## General

1. Please follow the provided format
1. We should prioritize the mock exam over notes

\part{Mock Exam}

\setcounter{section}{0}

# Basic Concepts and Principles

# Cryptographic Building Blocks

# User Authentication

# Authentication Protocols and Key Establishment

# Operating Systems Security and Access Control

# Software Security -- Privilege and Escalation

# Malicious Software

# Public Key Certificate Management and Use Cases

# Web and Browser Security

# Firewalls and Tunnels

# Intrusion Detection and Network-Based Attacks

\clearpage

\part{Notes}

\setcounter{section}{0}

# Basic Concepts and Principles

# Cryptographic Building Blocks

# User Authentication

# Authentication Protocols and Key Establishment

# Operating Systems Security and Access Control

# Software Security -- Privilege and Escalation

# Malicious Software

# Public Key Certificate Management and Use Cases

# Web and Browser Security

# Firewalls and Tunnels

# Intrusion Detection and Network-Based Attacks

<!-- References -->
\clearpage
